#!/bin/bash

URL="https://pokeapi.co/api/v2/pokemon/pikachu"
OUT_FILE="data.json"
ERROR_FILE="errors.txt"

curl -s -f "$URL" -o "$OUT_FILE"

if [ $? -ne 0 ]; then
  echo "Failed to fetch data from $URL" >> "$ERROR_FILE"
fi
